swagger: "2.0"
info:
  title: Task Service
  description: Service for manipulate task data
  version: ""
host: 0.0.0.0:8001
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /tasks:
    get:
      tags:
      - tasks
      summary: list tasks
      description: List all stored tasks
      operationId: tasks#list
      parameters:
      - name: view
        in: query
        description: View to render
        required: false
        type: string
        enum:
        - default
        - tiny
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/TasksStoredTaskResponseCollection'
      schemes:
      - http
    post:
      tags:
      - tasks
      summary: add tasks
      description: Add new task and return ID.
      operationId: tasks#add
      parameters:
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/TasksAddRequestBody'
          required:
          - title
          - description
          - created_date
          - updated_date
          - status
      responses:
        "201":
          description: Created response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
  /tasks/{id}:
    get:
      tags:
      - tasks
      summary: show tasks
      description: Show task by ID
      operationId: tasks#show
      parameters:
      - name: view
        in: query
        description: View to render
        required: false
        type: string
        enum:
        - default
        - tiny
      - name: id
        in: path
        description: ID of task to show
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/TasksShowResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/TasksShowNotFoundResponseBody'
            required:
            - message
            - id
      schemes:
      - http
    put:
      tags:
      - tasks
      summary: update tasks
      description: Update existing task and return ID.
      operationId: tasks#update
      parameters:
      - name: id
        in: path
        description: ID of task to show
        required: true
        type: string
      - name: UpdateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/TasksUpdateRequestBody'
          required:
          - task
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
    delete:
      tags:
      - tasks
      summary: remove tasks
      description: Remove task from tasks data
      operationId: tasks#remove
      parameters:
      - name: id
        in: path
        description: ID of task to remove
        required: true
        type: string
      responses:
        "204":
          description: No Content response.
      schemes:
      - http
  /tasks/status:
    put:
      tags:
      - tasks
      summary: status tasks
      description: change task status by id
      operationId: tasks#status
      parameters:
      - name: StatusRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/TasksStatusRequestBody'
          required:
          - id
          - status
      responses:
        "200":
          description: OK response.
      schemes:
      - http
definitions:
  StoredTaskRequestBody:
    title: 'Mediatype identifier: application/vnd.stored-task; view=default'
    type: object
    properties:
      assignee:
        type: string
        example: Accusamus et vel aspernatur et.
      created_date:
        type: string
        description: Created date
        example: "2004-08-16T16:45:02Z"
        format: date-time
      description:
        type: string
        description: Description of the task
        example: Task description
        maxLength: 5000
      id:
        type: string
        example: Quas aut.
      owner:
        type: string
        example: Nobis eum ipsum labore.
      status:
        type: string
        description: Status.
        default: Open
        example: Pending
        enum:
        - Open
        - Closed
        - Pending
      title:
        type: string
        description: Title of the task
        example: New task title
        maxLength: 200
      updated_date:
        type: string
        description: Udated date
        example: "1992-12-25T19:05:05Z"
        format: date-time
    description: A StoredTask describes a task retrieved by the tasks service. (default view)
    example:
      assignee: Quae voluptatem et distinctio.
      created_date: "2012-10-19T06:00:34Z"
      description: Task description
      id: Cupiditate sequi.
      owner: Temporibus molestias.
      status: Open
      title: New task title
      updated_date: "2012-05-12T08:43:23Z"
    required:
    - id
    - title
    - description
    - created_date
    - status
    - owner
    - updated_date
  StoredTaskResponse:
    title: 'Mediatype identifier: application/vnd.stored-task; view=default'
    type: object
    properties:
      assignee:
        type: string
        example: Fuga quasi qui in voluptas.
      created_date:
        type: string
        description: Created date
        example: "1989-10-13T12:27:39Z"
        format: date-time
      description:
        type: string
        description: Description of the task
        example: Task description
        maxLength: 5000
      id:
        type: string
        example: Sed et minima aut sunt.
      owner:
        type: string
        example: Magnam atque quae occaecati aut a.
      status:
        type: string
        description: Status.
        default: Open
        example: Open
        enum:
        - Open
        - Closed
        - Pending
      title:
        type: string
        description: Title of the task
        example: New task title
        maxLength: 200
      updated_date:
        type: string
        description: Udated date
        example: "2009-12-11T16:28:38Z"
        format: date-time
    description: A StoredTask describes a task retrieved by the tasks service. (default view)
    example:
      assignee: Et eos et non.
      created_date: "1995-12-15T01:16:46Z"
      description: Task description
      id: Quis recusandae.
      owner: Non saepe voluptas quae voluptatem omnis quaerat.
      status: Open
      title: New task title
      updated_date: "1994-02-15T11:22:43Z"
    required:
    - id
    - title
    - description
    - created_date
    - status
    - owner
    - updated_date
  TasksAddRequestBody:
    title: TasksAddRequestBody
    type: object
    properties:
      created_date:
        type: string
        description: Created date
        example: "2013-01-07T18:29:13Z"
        format: date-time
      description:
        type: string
        description: Description of the task
        example: Task description
        maxLength: 5000
      status:
        type: string
        description: Status.
        default: Open
        example: Pending
        enum:
        - Open
        - Closed
        - Pending
      title:
        type: string
        description: Title of the task
        example: New task title
        maxLength: 200
      updated_date:
        type: string
        description: Udated date
        example: "1978-08-30T13:55:58Z"
        format: date-time
    example:
      created_date: "1986-02-11T01:34:52Z"
      description: Task description
      status: Closed
      title: New task title
      updated_date: "2006-04-18T12:26:32Z"
    required:
    - title
    - description
    - created_date
    - updated_date
    - status
  TasksShowNotFoundResponseBody:
    title: TasksShowNotFoundResponseBody
    type: object
    properties:
      id:
        type: string
        description: ID of missing task
        example: Iste enim beatae alias distinctio.
      message:
        type: string
        description: Message of error
        example: task 1 not found
    description: Task not found
    example:
      id: Aliquid modi nisi.
      message: task 1 not found
    required:
    - message
    - id
  TasksShowResponseBody:
    title: 'Mediatype identifier: application/vnd.stored-task; view=default'
    type: object
    properties:
      assignee:
        type: string
        example: Quas dolorem harum iure eum reprehenderit.
      created_date:
        type: string
        description: Created date
        example: "1977-09-16T07:51:36Z"
        format: date-time
      description:
        type: string
        description: Description of the task
        example: Task description
        maxLength: 5000
      id:
        type: string
        example: Est molestias voluptas repellendus labore voluptatum.
      owner:
        type: string
        example: Nihil vel perspiciatis voluptas ipsa explicabo dolores.
      status:
        type: string
        description: Status.
        default: Open
        example: Pending
        enum:
        - Open
        - Closed
        - Pending
      title:
        type: string
        description: Title of the task
        example: New task title
        maxLength: 200
      updated_date:
        type: string
        description: Udated date
        example: "1977-06-05T11:39:55Z"
        format: date-time
    description: ShowResponseBody result type (default view)
    example:
      assignee: Non minima temporibus unde qui.
      created_date: "2007-01-11T01:25:10Z"
      description: Task description
      id: Incidunt repellat rerum.
      owner: Tempore molestiae totam numquam voluptatem tempora.
      status: Closed
      title: New task title
      updated_date: "1990-10-25T08:22:05Z"
    required:
    - id
    - title
    - description
    - created_date
    - status
    - owner
    - updated_date
  TasksStatusRequestBody:
    title: TasksStatusRequestBody
    type: object
    properties:
      id:
        type: string
        description: ID of task
        example: Impedit ipsum blanditiis in odio.
      status:
        type: string
        description: Status.
        default: Open
        example: Open
        enum:
        - Open
        - Closed
        - Pending
    example:
      id: Vel tempora incidunt sint soluta quis numquam.
      status: Closed
    required:
    - id
    - status
  TasksStoredTaskResponseCollection:
    title: 'Mediatype identifier: application/vnd.stored-task; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/StoredTaskResponse'
    description: ListResponseBody is the result type for an array of StoredTaskResponse (default view)
    example:
    - assignee: Ad asperiores qui ut veniam.
      created_date: "2009-02-01T18:33:09Z"
      description: Task description
      id: Et praesentium suscipit beatae qui rerum qui.
      owner: Quis odio consectetur non.
      status: Closed
      title: New task title
      updated_date: "2012-08-04T10:28:18Z"
    - assignee: Ad asperiores qui ut veniam.
      created_date: "2009-02-01T18:33:09Z"
      description: Task description
      id: Et praesentium suscipit beatae qui rerum qui.
      owner: Quis odio consectetur non.
      status: Closed
      title: New task title
      updated_date: "2012-08-04T10:28:18Z"
    - assignee: Ad asperiores qui ut veniam.
      created_date: "2009-02-01T18:33:09Z"
      description: Task description
      id: Et praesentium suscipit beatae qui rerum qui.
      owner: Quis odio consectetur non.
      status: Closed
      title: New task title
      updated_date: "2012-08-04T10:28:18Z"
  TasksUpdateRequestBody:
    title: TasksUpdateRequestBody
    type: object
    properties:
      task:
        $ref: '#/definitions/StoredTaskRequestBody'
    example:
      task:
        assignee: Recusandae ipsum.
        created_date: "1977-08-23T17:31:33Z"
        description: Task description
        due_date: Dignissimos non assumenda tenetur voluptatum id quo.
        id: Dolor eos dolorem numquam odio aspernatur et.
        owner: Vero molestiae similique enim libero quia animi.
        status: Closed
        title: New task title
        updated_date: "1994-11-14T18:35:02Z"
    required:
    - task
